print("Hello World!")
print("         *")
print("        **")
print("       ***")
print("      ****")
print("     *****")
print("    ******")
print("   *******")
print("  ********")
print(" *********")
print("**********")
print("Hello world")
print("Hello India","Hello world","Hi Python students")
print(10)
print (20.5)
print("Hello India",10,20.5)

r=int(input())
v=4/3*3.14*r*r*r
print(v)
print("Hello World")